### ISSUE TITLE
AttributeError: module 'chainer.functions' has no attribute 'ReLU'

### ISSUE THREAD

**Issue by zhengziqiang** [hvy/chainer-inception-score#5] opened 2018-10-28 13:03 UTC
The chainer version problem

**Comment by hvy** [comment] 2018-11-01 13:04
Thanks a lot for the report. It was caused by `FunctionNode`s becoming private. It should be fixed now.

**Comment by zhengziqiang** [comment] 2018-11-05 00:08
Thank you so much!

**Comment by hvy** [comment] 2018-11-05 00:57
Great, let me close this ticket as fixed.

**Closed as completed by hvy** 2018-11-05 00:57 UTC
